spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Hibernate actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formato SQL (opcional)
spring.jpa.properties.hibernate.format_sql=true

# Driver PostgreSQL (IMPORTANTE)
spring.datasource.driver-class-name=org.postgresql.Driver

# Puerto dinámico de Railway (CRÍTICO)
server.port=${PORT:8080}
